<?php

/**
 * HtmlElement.php
 *
 * The HTML UI tags generated by the Builder engine.
 *
 * @package ui-builder-html
 * @author Thierry Feuzeu <thierry.feuzeu@gmail.com>
 * @copyright 2026 Thierry Feuzeu <thierry.feuzeu@gmail.com>
 * @license https://opensource.org/license/mit The MIT License
 * @link https://github.com/lagdo/ui-builder-html
 */

namespace Lagdo\UiBuilder\Html;

use Lagdo\UiBuilder\Html\Element\Element;

use function array_filter;
use function array_keys;
use function count;
use function htmlspecialchars;
use function implode;
use function is_a;
use function is_bool;
use function is_numeric;
use function is_string;
use function sprintf;
use function trim;

/**
 * @method static setId(string $id, bool $escape = true)
 * @method static setClass(string $class, bool $escape = true)
 * @method static setFor(string $for, bool $escape = true)
 * @method static setName(string $name, bool $escape = true)
 * @method static setValue(string $value, bool $escape = true)
 * @method static setType(string $type, bool $escape = true)
 * @method static setTitle(string $type, bool $escape = true)
 * @method static setStyle(string $type, bool $escape = true)
 */
class HtmlElement extends Element
{
    /**
     * @var bool
     */
    private bool $isShort = false;

    /**
     * @var bool
     */
    private bool $isOpened = false;

    /**
     * @var array
     */
    private array $attributes = [];

    /**
     * @var array
     */
    private array $escapes = [];

    /**
     * @var array
     */
    private array $classes = [];

    /**
     * @var array<Element>
     */
    private array $children = [];

    /**
     * @param HtmlComponent $component
     * @param string $tag
     * @param array $attributes
     */
    public function __construct(private HtmlComponent $component,
        private string $tag, array $attributes = [])
    {
        $this->setAttributes($attributes);
    }

    /**
     * @param string $method
     * @param array $arguments
     *
     * @return static
     */
    public function __call(string $method, array $arguments): static
    {
        $this->component->engine->callElementHelper($this, $method, $arguments);
        return $this;
    }

    /**
     * @return string
     */
    public function tag(): string
    {
        return $this->tag;
    }

    /**
     * @param string $tag
     *
     * @return static
     */
    public function setTag(string $tag): static
    {
        $this->tag = $tag;
        return $this;
    }

    /**
     * @param array<Element> $children
     *
     * @return static
     */
    public function setChildren(array $children): static
    {
        $this->children = $children;
        return $this;
    }

    /**
     * @param array<Element> $children
     *
     * @return static
     */
    public function addChildren(array $children): static
    {
        $children = array_filter($children, fn($child) => is_a($child, Element::class));
        $this->children = [...$this->children, ...$children];
        return $this;
    }

    /**
     * @param Element $child
     *
     * @return static
     */
    public function addChild(Element $child): static
    {
        $this->children[] = $child;
        return $this;
    }

    /**
     * @param string $class
     *
     * @return static
     */
    public function addClass(string $class): static
    {
        $this->classes[trim($class)] = true;
        return $this;
    }

    /**
     * @param string $class
     *
     * @return static
     */
    public function setClass(string $class): static
    {
        // Actually appends the class.
        $this->addClass($class);
        return $this;
    }

    /**
     * @param string $class
     *
     * @return static
     */
    public function removeClass(string $class): static
    {
        $this->classes[trim($class)] = false;
        return $this;
    }

    /**
     * @param string $class
     *
     * @return bool
     */
    public function hasClass(string $class): bool
    {
        return ($this->classes[trim($class)] ?? false) === true;
    }

    /**
     * Get the classes in the format they are stored.
     *
     * @return array
     */
    public function getRawClasses(): array
    {
        return $this->classes;
    }

    /**
     * Set the classes, already in the right format.
     *
     * @param array $classes
     *
     * @return void
     */
    public function setRawClasses(array $classes): void
    {
        $this->classes = $classes;
    }

    /**
     * @param bool $isShort
     *
     * @return static
     */
    public function setShort(bool $isShort): static
    {
        $this->isShort = $isShort;
        return $this;
    }

    /**
     * @param bool $isOpened
     *
     * @return void
     */
    public function setOpened(bool $isOpened): void
    {
        $this->isOpened = $isOpened;
    }

    /**
     * @param string $name
     * @param string|bool $value
     * @param bool $escape
     *
     * @return static
     */
    public function setAttribute(string $name, string|bool $value = true, bool $escape = true): static
    {
        $this->attributes[$name] = $value;
        $this->escapes[$name] = $escape;
        return $this;
    }

    /**
     * @param array $attributes
     * @param bool $escape
     *
     * @return static
     */
    public function setAttributes(array $attributes, bool $escape = true): static
    {
        foreach ($attributes as $name => $value) {
            switch (true) {
                case is_numeric($name):
                    $this->setAttribute($value);
                    break;
                case is_string($value):
                case is_bool($value):
                    $this->setAttribute($name, $value, $escape);
                    break;
                default: // Any other values are ignored.
            }
        }
        return $this;
    }

    /**
     * @param string $name
     *
     * @return bool
     */
    public function hasAttribute(string $name): bool
    {
        return isset($this->attributes[$name]) && $this->attributes[$name] !== false;
    }

    /**
     * @param string $name
     *
     * @return string|bool
     */
    public function getAttribute(string $name): string|bool
    {
        return $this->attributes[$name] ?? false;
    }

    /**
     * @param string $name
     *
     * @return static
     */
    public function removeAttribute(string $name): static
    {
        $this->attributes[$name] = false;
        return $this;
    }

    /**
     * @return string
     */
    private function renderAttributes(): string
    {
        // Merge the classes.
        $classes = array_keys(array_filter($this->classes, fn($active) => $active === true));
        if (isset($this->attributes['class'])) {
            $classes[] = $this->attributes['class'];
        }
        if (($class = trim(implode(' ', $classes))) !== '') {
            $this->attributes['class'] = $class;
        }

        $attributes = [];
        foreach ($this->attributes as $name => $value) {
            // Attributes with false as value are ignored.
            if ($value !== false) {
                $name = $this->escape($name);
                if ($value === true) {
                    $attributes[] = $name;
                    continue;
                }

                if (($this->escapes[$name] ?? true) === true) {
                    $value = $this->escape($value);
                }
                $attributes[] = "$name=\"$value\"";
            }
        }

        return count($attributes) === 0 ? '' : ' ' . implode(' ', $attributes);
    }

    /**
     * @return string
     */
    private function renderShort(): string
    {
        return sprintf('<%s%s />', $this->tag, $this->renderAttributes());
    }

    /**
     * @return string
     */
    private function renderOpened(): string
    {
        return sprintf('<%s%s>', $this->tag, $this->renderAttributes());
    }

    /**
     * @return string
     */
    private function renderTag(): string
    {
        $children = implode('', $this->children);
        return sprintf('%s%s</%s>', $this->renderOpened(), $children, $this->tag);
    }

    /**
     * @param string|bool $value
     *
     * @return string
     */
    private function escape(string|bool $value): string
    {
        return is_bool($value) ? $value : htmlspecialchars($value, ENT_COMPAT);
    }

    /**
     * @inheritDoc
     */
    protected function render(): string
    {
        return match(true) {
            $this->isShort => $this->renderShort(),
            $this->isOpened => $this->renderOpened(),
            default => $this->renderTag(),
        };
    }
}
